@startuml
autonumber
skinparam ParticipantPadding 30
skinparam BoxPadding 20

Box Sender
  participant "Sender System" as Sender
  participant SenderNode
end box
Box Receiver
  participant ReceiverNode
  participant "Receiving System" as Receiver
end box

activate Sender
Sender -> SenderNode: Find eOverdracht-receiver service
SenderNode -> Sender: <<Service>>
group "Request access token"
  Sender <-> ReceiverNode: Request access token
end

Sender -> Receiver: Notify
activate Receiver
Receiver -> ReceiverNode: Validate <<accessToken>>
activate ReceiverNode
ReceiverNode --> Receiver: Ok
deactivate ReceiverNode
Receiver --> Sender: Ok
deactivate Receiver
deactivate Sender


@enduml
